#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWebDatTourDuLich.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LapTrinhWebDatTourDuLich")]
	public partial class MyDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_Tour(Table_Tour instance);
    partial void UpdateTable_Tour(Table_Tour instance);
    partial void DeleteTable_Tour(Table_Tour instance);
    partial void InsertTable_ThanhToan(Table_ThanhToan instance);
    partial void UpdateTable_ThanhToan(Table_ThanhToan instance);
    partial void DeleteTable_ThanhToan(Table_ThanhToan instance);
    partial void InsertTable_LoaiVanChuyen(Table_LoaiVanChuyen instance);
    partial void UpdateTable_LoaiVanChuyen(Table_LoaiVanChuyen instance);
    partial void DeleteTable_LoaiVanChuyen(Table_LoaiVanChuyen instance);
    partial void InsertTable_KhachHang(Table_KhachHang instance);
    partial void UpdateTable_KhachHang(Table_KhachHang instance);
    partial void DeleteTable_KhachHang(Table_KhachHang instance);
    partial void InsertTable_DonTour(Table_DonTour instance);
    partial void UpdateTable_DonTour(Table_DonTour instance);
    partial void DeleteTable_DonTour(Table_DonTour instance);
    partial void InsertTable_ChiTietDonTour(Table_ChiTietDonTour instance);
    partial void UpdateTable_ChiTietDonTour(Table_ChiTietDonTour instance);
    partial void DeleteTable_ChiTietDonTour(Table_ChiTietDonTour instance);
    #endregion
		
		public MyDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LapTrinhWebDatTourDuLichConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_Tour> Table_Tours
		{
			get
			{
				return this.GetTable<Table_Tour>();
			}
		}
		
		public System.Data.Linq.Table<Table_ThanhToan> Table_ThanhToans
		{
			get
			{
				return this.GetTable<Table_ThanhToan>();
			}
		}
		
		public System.Data.Linq.Table<Table_LoaiVanChuyen> Table_LoaiVanChuyens
		{
			get
			{
				return this.GetTable<Table_LoaiVanChuyen>();
			}
		}
		
		public System.Data.Linq.Table<Table_KhachHang> Table_KhachHangs
		{
			get
			{
				return this.GetTable<Table_KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<Table_DonTour> Table_DonTours
		{
			get
			{
				return this.GetTable<Table_DonTour>();
			}
		}
		
		public System.Data.Linq.Table<Table_ChiTietDonTour> Table_ChiTietDonTours
		{
			get
			{
				return this.GetTable<Table_ChiTietDonTour>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Tour")]
	public partial class Table_Tour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTour;
		
		private System.Nullable<int> _MaVanChuyen;
		
		private string _TenTour;
		
		private string _NoiKhoiHanh;
		
		private System.Nullable<System.DateTime> _NgayKhoiHanh;
		
		private string _ThoiGian;
		
		private System.Nullable<decimal> _GiaTour;
		
		private string _TourNayCoGiHay;
		
		private string _Hinh;
		
		private EntitySet<Table_ThanhToan> _Table_ThanhToans;
		
		private EntitySet<Table_ChiTietDonTour> _Table_ChiTietDonTours;
		
		private EntityRef<Table_LoaiVanChuyen> _Table_LoaiVanChuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTourChanging(int value);
    partial void OnMaTourChanged();
    partial void OnMaVanChuyenChanging(System.Nullable<int> value);
    partial void OnMaVanChuyenChanged();
    partial void OnTenTourChanging(string value);
    partial void OnTenTourChanged();
    partial void OnNoiKhoiHanhChanging(string value);
    partial void OnNoiKhoiHanhChanged();
    partial void OnNgayKhoiHanhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKhoiHanhChanged();
    partial void OnThoiGianChanging(string value);
    partial void OnThoiGianChanged();
    partial void OnGiaTourChanging(System.Nullable<decimal> value);
    partial void OnGiaTourChanged();
    partial void OnTourNayCoGiHayChanging(string value);
    partial void OnTourNayCoGiHayChanged();
    partial void OnHinhChanging(string value);
    partial void OnHinhChanged();
    #endregion
		
		public Table_Tour()
		{
			this._Table_ThanhToans = new EntitySet<Table_ThanhToan>(new Action<Table_ThanhToan>(this.attach_Table_ThanhToans), new Action<Table_ThanhToan>(this.detach_Table_ThanhToans));
			this._Table_ChiTietDonTours = new EntitySet<Table_ChiTietDonTour>(new Action<Table_ChiTietDonTour>(this.attach_Table_ChiTietDonTours), new Action<Table_ChiTietDonTour>(this.detach_Table_ChiTietDonTours));
			this._Table_LoaiVanChuyen = default(EntityRef<Table_LoaiVanChuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVanChuyen", DbType="Int")]
		public System.Nullable<int> MaVanChuyen
		{
			get
			{
				return this._MaVanChuyen;
			}
			set
			{
				if ((this._MaVanChuyen != value))
				{
					if (this._Table_LoaiVanChuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaVanChuyenChanging(value);
					this.SendPropertyChanging();
					this._MaVanChuyen = value;
					this.SendPropertyChanged("MaVanChuyen");
					this.OnMaVanChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTour", DbType="NVarChar(100)")]
		public string TenTour
		{
			get
			{
				return this._TenTour;
			}
			set
			{
				if ((this._TenTour != value))
				{
					this.OnTenTourChanging(value);
					this.SendPropertyChanging();
					this._TenTour = value;
					this.SendPropertyChanged("TenTour");
					this.OnTenTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiKhoiHanh", DbType="NVarChar(20)")]
		public string NoiKhoiHanh
		{
			get
			{
				return this._NoiKhoiHanh;
			}
			set
			{
				if ((this._NoiKhoiHanh != value))
				{
					this.OnNoiKhoiHanhChanging(value);
					this.SendPropertyChanging();
					this._NoiKhoiHanh = value;
					this.SendPropertyChanged("NoiKhoiHanh");
					this.OnNoiKhoiHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKhoiHanh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKhoiHanh
		{
			get
			{
				return this._NgayKhoiHanh;
			}
			set
			{
				if ((this._NgayKhoiHanh != value))
				{
					this.OnNgayKhoiHanhChanging(value);
					this.SendPropertyChanging();
					this._NgayKhoiHanh = value;
					this.SendPropertyChanged("NgayKhoiHanh");
					this.OnNgayKhoiHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="NVarChar(20)")]
		public string ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTour", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GiaTour
		{
			get
			{
				return this._GiaTour;
			}
			set
			{
				if ((this._GiaTour != value))
				{
					this.OnGiaTourChanging(value);
					this.SendPropertyChanging();
					this._GiaTour = value;
					this.SendPropertyChanged("GiaTour");
					this.OnGiaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TourNayCoGiHay", DbType="NVarChar(2000)")]
		public string TourNayCoGiHay
		{
			get
			{
				return this._TourNayCoGiHay;
			}
			set
			{
				if ((this._TourNayCoGiHay != value))
				{
					this.OnTourNayCoGiHayChanging(value);
					this.SendPropertyChanging();
					this._TourNayCoGiHay = value;
					this.SendPropertyChanged("TourNayCoGiHay");
					this.OnTourNayCoGiHayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh", DbType="VarChar(50)")]
		public string Hinh
		{
			get
			{
				return this._Hinh;
			}
			set
			{
				if ((this._Hinh != value))
				{
					this.OnHinhChanging(value);
					this.SendPropertyChanging();
					this._Hinh = value;
					this.SendPropertyChanged("Hinh");
					this.OnHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_Tour_Table_ThanhToan", Storage="_Table_ThanhToans", ThisKey="MaTour", OtherKey="MaTour")]
		public EntitySet<Table_ThanhToan> Table_ThanhToans
		{
			get
			{
				return this._Table_ThanhToans;
			}
			set
			{
				this._Table_ThanhToans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_Tour_Table_ChiTietDonTour", Storage="_Table_ChiTietDonTours", ThisKey="MaTour", OtherKey="MaTour")]
		public EntitySet<Table_ChiTietDonTour> Table_ChiTietDonTours
		{
			get
			{
				return this._Table_ChiTietDonTours;
			}
			set
			{
				this._Table_ChiTietDonTours.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_LoaiVanChuyen_Table_Tour", Storage="_Table_LoaiVanChuyen", ThisKey="MaVanChuyen", OtherKey="MaVanChuyen", IsForeignKey=true)]
		public Table_LoaiVanChuyen Table_LoaiVanChuyen
		{
			get
			{
				return this._Table_LoaiVanChuyen.Entity;
			}
			set
			{
				Table_LoaiVanChuyen previousValue = this._Table_LoaiVanChuyen.Entity;
				if (((previousValue != value) 
							|| (this._Table_LoaiVanChuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_LoaiVanChuyen.Entity = null;
						previousValue.Table_Tours.Remove(this);
					}
					this._Table_LoaiVanChuyen.Entity = value;
					if ((value != null))
					{
						value.Table_Tours.Add(this);
						this._MaVanChuyen = value.MaVanChuyen;
					}
					else
					{
						this._MaVanChuyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_LoaiVanChuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_ThanhToans(Table_ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.Table_Tour = this;
		}
		
		private void detach_Table_ThanhToans(Table_ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.Table_Tour = null;
		}
		
		private void attach_Table_ChiTietDonTours(Table_ChiTietDonTour entity)
		{
			this.SendPropertyChanging();
			entity.Table_Tour = this;
		}
		
		private void detach_Table_ChiTietDonTours(Table_ChiTietDonTour entity)
		{
			this.SendPropertyChanging();
			entity.Table_Tour = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_ThanhToan")]
	public partial class Table_ThanhToan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThanhToan;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<int> _MaDonTour;
		
		private System.Nullable<int> _MaTour;
		
		private System.Nullable<decimal> _TongSoTienPhaiThanhToan;
		
		private System.Nullable<decimal> _SoTienDaThanhToan;
		
		private string _GhiChu;
		
		private EntityRef<Table_Tour> _Table_Tour;
		
		private EntityRef<Table_KhachHang> _Table_KhachHang;
		
		private EntityRef<Table_DonTour> _Table_DonTour;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThanhToanChanging(int value);
    partial void OnMaThanhToanChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnMaDonTourChanging(System.Nullable<int> value);
    partial void OnMaDonTourChanged();
    partial void OnMaTourChanging(System.Nullable<int> value);
    partial void OnMaTourChanged();
    partial void OnTongSoTienPhaiThanhToanChanging(System.Nullable<decimal> value);
    partial void OnTongSoTienPhaiThanhToanChanged();
    partial void OnSoTienDaThanhToanChanging(System.Nullable<decimal> value);
    partial void OnSoTienDaThanhToanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public Table_ThanhToan()
		{
			this._Table_Tour = default(EntityRef<Table_Tour>);
			this._Table_KhachHang = default(EntityRef<Table_KhachHang>);
			this._Table_DonTour = default(EntityRef<Table_DonTour>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhToan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaThanhToan
		{
			get
			{
				return this._MaThanhToan;
			}
			set
			{
				if ((this._MaThanhToan != value))
				{
					this.OnMaThanhToanChanging(value);
					this.SendPropertyChanging();
					this._MaThanhToan = value;
					this.SendPropertyChanged("MaThanhToan");
					this.OnMaThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._Table_KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonTour", DbType="Int")]
		public System.Nullable<int> MaDonTour
		{
			get
			{
				return this._MaDonTour;
			}
			set
			{
				if ((this._MaDonTour != value))
				{
					if (this._Table_DonTour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonTourChanging(value);
					this.SendPropertyChanging();
					this._MaDonTour = value;
					this.SendPropertyChanged("MaDonTour");
					this.OnMaDonTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="Int")]
		public System.Nullable<int> MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					if (this._Table_Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoTienPhaiThanhToan", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TongSoTienPhaiThanhToan
		{
			get
			{
				return this._TongSoTienPhaiThanhToan;
			}
			set
			{
				if ((this._TongSoTienPhaiThanhToan != value))
				{
					this.OnTongSoTienPhaiThanhToanChanging(value);
					this.SendPropertyChanging();
					this._TongSoTienPhaiThanhToan = value;
					this.SendPropertyChanged("TongSoTienPhaiThanhToan");
					this.OnTongSoTienPhaiThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienDaThanhToan", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoTienDaThanhToan
		{
			get
			{
				return this._SoTienDaThanhToan;
			}
			set
			{
				if ((this._SoTienDaThanhToan != value))
				{
					this.OnSoTienDaThanhToanChanging(value);
					this.SendPropertyChanging();
					this._SoTienDaThanhToan = value;
					this.SendPropertyChanged("SoTienDaThanhToan");
					this.OnSoTienDaThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(100)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_Tour_Table_ThanhToan", Storage="_Table_Tour", ThisKey="MaTour", OtherKey="MaTour", IsForeignKey=true)]
		public Table_Tour Table_Tour
		{
			get
			{
				return this._Table_Tour.Entity;
			}
			set
			{
				Table_Tour previousValue = this._Table_Tour.Entity;
				if (((previousValue != value) 
							|| (this._Table_Tour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_Tour.Entity = null;
						previousValue.Table_ThanhToans.Remove(this);
					}
					this._Table_Tour.Entity = value;
					if ((value != null))
					{
						value.Table_ThanhToans.Add(this);
						this._MaTour = value.MaTour;
					}
					else
					{
						this._MaTour = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_Tour");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_KhachHang_Table_ThanhToan", Storage="_Table_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public Table_KhachHang Table_KhachHang
		{
			get
			{
				return this._Table_KhachHang.Entity;
			}
			set
			{
				Table_KhachHang previousValue = this._Table_KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._Table_KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_KhachHang.Entity = null;
						previousValue.Table_ThanhToans.Remove(this);
					}
					this._Table_KhachHang.Entity = value;
					if ((value != null))
					{
						value.Table_ThanhToans.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_DonTour_Table_ThanhToan", Storage="_Table_DonTour", ThisKey="MaDonTour", OtherKey="MaDonTour", IsForeignKey=true)]
		public Table_DonTour Table_DonTour
		{
			get
			{
				return this._Table_DonTour.Entity;
			}
			set
			{
				Table_DonTour previousValue = this._Table_DonTour.Entity;
				if (((previousValue != value) 
							|| (this._Table_DonTour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_DonTour.Entity = null;
						previousValue.Table_ThanhToans.Remove(this);
					}
					this._Table_DonTour.Entity = value;
					if ((value != null))
					{
						value.Table_ThanhToans.Add(this);
						this._MaDonTour = value.MaDonTour;
					}
					else
					{
						this._MaDonTour = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_DonTour");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_LoaiVanChuyen")]
	public partial class Table_LoaiVanChuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaVanChuyen;
		
		private string _LoaiVanChuyen;
		
		private EntitySet<Table_Tour> _Table_Tours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVanChuyenChanging(int value);
    partial void OnMaVanChuyenChanged();
    partial void OnLoaiVanChuyenChanging(string value);
    partial void OnLoaiVanChuyenChanged();
    #endregion
		
		public Table_LoaiVanChuyen()
		{
			this._Table_Tours = new EntitySet<Table_Tour>(new Action<Table_Tour>(this.attach_Table_Tours), new Action<Table_Tour>(this.detach_Table_Tours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVanChuyen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaVanChuyen
		{
			get
			{
				return this._MaVanChuyen;
			}
			set
			{
				if ((this._MaVanChuyen != value))
				{
					this.OnMaVanChuyenChanging(value);
					this.SendPropertyChanging();
					this._MaVanChuyen = value;
					this.SendPropertyChanged("MaVanChuyen");
					this.OnMaVanChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiVanChuyen", DbType="NVarChar(20)")]
		public string LoaiVanChuyen
		{
			get
			{
				return this._LoaiVanChuyen;
			}
			set
			{
				if ((this._LoaiVanChuyen != value))
				{
					this.OnLoaiVanChuyenChanging(value);
					this.SendPropertyChanging();
					this._LoaiVanChuyen = value;
					this.SendPropertyChanged("LoaiVanChuyen");
					this.OnLoaiVanChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_LoaiVanChuyen_Table_Tour", Storage="_Table_Tours", ThisKey="MaVanChuyen", OtherKey="MaVanChuyen")]
		public EntitySet<Table_Tour> Table_Tours
		{
			get
			{
				return this._Table_Tours;
			}
			set
			{
				this._Table_Tours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_Tours(Table_Tour entity)
		{
			this.SendPropertyChanging();
			entity.Table_LoaiVanChuyen = this;
		}
		
		private void detach_Table_Tours(Table_Tour entity)
		{
			this.SendPropertyChanging();
			entity.Table_LoaiVanChuyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_KhachHang")]
	public partial class Table_KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _TaiKhoanDangNhap;
		
		private string _MatKhauDangNhap;
		
		private string _HoTenKH;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private EntitySet<Table_ThanhToan> _Table_ThanhToans;
		
		private EntitySet<Table_DonTour> _Table_DonTours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnTaiKhoanDangNhapChanging(string value);
    partial void OnTaiKhoanDangNhapChanged();
    partial void OnMatKhauDangNhapChanging(string value);
    partial void OnMatKhauDangNhapChanged();
    partial void OnHoTenKHChanging(string value);
    partial void OnHoTenKHChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    #endregion
		
		public Table_KhachHang()
		{
			this._Table_ThanhToans = new EntitySet<Table_ThanhToan>(new Action<Table_ThanhToan>(this.attach_Table_ThanhToans), new Action<Table_ThanhToan>(this.detach_Table_ThanhToans));
			this._Table_DonTours = new EntitySet<Table_DonTour>(new Action<Table_DonTour>(this.attach_Table_DonTours), new Action<Table_DonTour>(this.detach_Table_DonTours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanDangNhap", DbType="VarChar(20)")]
		public string TaiKhoanDangNhap
		{
			get
			{
				return this._TaiKhoanDangNhap;
			}
			set
			{
				if ((this._TaiKhoanDangNhap != value))
				{
					this.OnTaiKhoanDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanDangNhap = value;
					this.SendPropertyChanged("TaiKhoanDangNhap");
					this.OnTaiKhoanDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauDangNhap", DbType="VarChar(20)")]
		public string MatKhauDangNhap
		{
			get
			{
				return this._MatKhauDangNhap;
			}
			set
			{
				if ((this._MatKhauDangNhap != value))
				{
					this.OnMatKhauDangNhapChanging(value);
					this.SendPropertyChanging();
					this._MatKhauDangNhap = value;
					this.SendPropertyChanged("MatKhauDangNhap");
					this.OnMatKhauDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenKH", DbType="NVarChar(50)")]
		public string HoTenKH
		{
			get
			{
				return this._HoTenKH;
			}
			set
			{
				if ((this._HoTenKH != value))
				{
					this.OnHoTenKHChanging(value);
					this.SendPropertyChanging();
					this._HoTenKH = value;
					this.SendPropertyChanged("HoTenKH");
					this.OnHoTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(15)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_KhachHang_Table_ThanhToan", Storage="_Table_ThanhToans", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<Table_ThanhToan> Table_ThanhToans
		{
			get
			{
				return this._Table_ThanhToans;
			}
			set
			{
				this._Table_ThanhToans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_KhachHang_Table_DonTour", Storage="_Table_DonTours", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<Table_DonTour> Table_DonTours
		{
			get
			{
				return this._Table_DonTours;
			}
			set
			{
				this._Table_DonTours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_ThanhToans(Table_ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.Table_KhachHang = this;
		}
		
		private void detach_Table_ThanhToans(Table_ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.Table_KhachHang = null;
		}
		
		private void attach_Table_DonTours(Table_DonTour entity)
		{
			this.SendPropertyChanging();
			entity.Table_KhachHang = this;
		}
		
		private void detach_Table_DonTours(Table_DonTour entity)
		{
			this.SendPropertyChanging();
			entity.Table_KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_DonTour")]
	public partial class Table_DonTour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonTour;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<System.DateTime> _NgayDatTour;
		
		private EntitySet<Table_ThanhToan> _Table_ThanhToans;
		
		private EntitySet<Table_ChiTietDonTour> _Table_ChiTietDonTours;
		
		private EntityRef<Table_KhachHang> _Table_KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonTourChanging(int value);
    partial void OnMaDonTourChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnNgayDatTourChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatTourChanged();
    #endregion
		
		public Table_DonTour()
		{
			this._Table_ThanhToans = new EntitySet<Table_ThanhToan>(new Action<Table_ThanhToan>(this.attach_Table_ThanhToans), new Action<Table_ThanhToan>(this.detach_Table_ThanhToans));
			this._Table_ChiTietDonTours = new EntitySet<Table_ChiTietDonTour>(new Action<Table_ChiTietDonTour>(this.attach_Table_ChiTietDonTours), new Action<Table_ChiTietDonTour>(this.detach_Table_ChiTietDonTours));
			this._Table_KhachHang = default(EntityRef<Table_KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonTour", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDonTour
		{
			get
			{
				return this._MaDonTour;
			}
			set
			{
				if ((this._MaDonTour != value))
				{
					this.OnMaDonTourChanging(value);
					this.SendPropertyChanging();
					this._MaDonTour = value;
					this.SendPropertyChanged("MaDonTour");
					this.OnMaDonTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._Table_KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDatTour", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDatTour
		{
			get
			{
				return this._NgayDatTour;
			}
			set
			{
				if ((this._NgayDatTour != value))
				{
					this.OnNgayDatTourChanging(value);
					this.SendPropertyChanging();
					this._NgayDatTour = value;
					this.SendPropertyChanged("NgayDatTour");
					this.OnNgayDatTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_DonTour_Table_ThanhToan", Storage="_Table_ThanhToans", ThisKey="MaDonTour", OtherKey="MaDonTour")]
		public EntitySet<Table_ThanhToan> Table_ThanhToans
		{
			get
			{
				return this._Table_ThanhToans;
			}
			set
			{
				this._Table_ThanhToans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_DonTour_Table_ChiTietDonTour", Storage="_Table_ChiTietDonTours", ThisKey="MaDonTour", OtherKey="MaDonTour")]
		public EntitySet<Table_ChiTietDonTour> Table_ChiTietDonTours
		{
			get
			{
				return this._Table_ChiTietDonTours;
			}
			set
			{
				this._Table_ChiTietDonTours.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_KhachHang_Table_DonTour", Storage="_Table_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public Table_KhachHang Table_KhachHang
		{
			get
			{
				return this._Table_KhachHang.Entity;
			}
			set
			{
				Table_KhachHang previousValue = this._Table_KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._Table_KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_KhachHang.Entity = null;
						previousValue.Table_DonTours.Remove(this);
					}
					this._Table_KhachHang.Entity = value;
					if ((value != null))
					{
						value.Table_DonTours.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_ThanhToans(Table_ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.Table_DonTour = this;
		}
		
		private void detach_Table_ThanhToans(Table_ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.Table_DonTour = null;
		}
		
		private void attach_Table_ChiTietDonTours(Table_ChiTietDonTour entity)
		{
			this.SendPropertyChanging();
			entity.Table_DonTour = this;
		}
		
		private void detach_Table_ChiTietDonTours(Table_ChiTietDonTour entity)
		{
			this.SendPropertyChanging();
			entity.Table_DonTour = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_ChiTietDonTour")]
	public partial class Table_ChiTietDonTour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonTour;
		
		private int _MaTour;
		
		private System.Nullable<int> _SoVe;
		
		private System.Nullable<decimal> _GiaDonTour;
		
		private EntityRef<Table_DonTour> _Table_DonTour;
		
		private EntityRef<Table_Tour> _Table_Tour;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonTourChanging(int value);
    partial void OnMaDonTourChanged();
    partial void OnMaTourChanging(int value);
    partial void OnMaTourChanged();
    partial void OnSoVeChanging(System.Nullable<int> value);
    partial void OnSoVeChanged();
    partial void OnGiaDonTourChanging(System.Nullable<decimal> value);
    partial void OnGiaDonTourChanged();
    #endregion
		
		public Table_ChiTietDonTour()
		{
			this._Table_DonTour = default(EntityRef<Table_DonTour>);
			this._Table_Tour = default(EntityRef<Table_Tour>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonTour", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDonTour
		{
			get
			{
				return this._MaDonTour;
			}
			set
			{
				if ((this._MaDonTour != value))
				{
					if (this._Table_DonTour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonTourChanging(value);
					this.SendPropertyChanging();
					this._MaDonTour = value;
					this.SendPropertyChanged("MaDonTour");
					this.OnMaDonTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					if (this._Table_Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoVe", DbType="Int")]
		public System.Nullable<int> SoVe
		{
			get
			{
				return this._SoVe;
			}
			set
			{
				if ((this._SoVe != value))
				{
					this.OnSoVeChanging(value);
					this.SendPropertyChanging();
					this._SoVe = value;
					this.SendPropertyChanged("SoVe");
					this.OnSoVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaDonTour", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GiaDonTour
		{
			get
			{
				return this._GiaDonTour;
			}
			set
			{
				if ((this._GiaDonTour != value))
				{
					this.OnGiaDonTourChanging(value);
					this.SendPropertyChanging();
					this._GiaDonTour = value;
					this.SendPropertyChanged("GiaDonTour");
					this.OnGiaDonTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_DonTour_Table_ChiTietDonTour", Storage="_Table_DonTour", ThisKey="MaDonTour", OtherKey="MaDonTour", IsForeignKey=true)]
		public Table_DonTour Table_DonTour
		{
			get
			{
				return this._Table_DonTour.Entity;
			}
			set
			{
				Table_DonTour previousValue = this._Table_DonTour.Entity;
				if (((previousValue != value) 
							|| (this._Table_DonTour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_DonTour.Entity = null;
						previousValue.Table_ChiTietDonTours.Remove(this);
					}
					this._Table_DonTour.Entity = value;
					if ((value != null))
					{
						value.Table_ChiTietDonTours.Add(this);
						this._MaDonTour = value.MaDonTour;
					}
					else
					{
						this._MaDonTour = default(int);
					}
					this.SendPropertyChanged("Table_DonTour");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_Tour_Table_ChiTietDonTour", Storage="_Table_Tour", ThisKey="MaTour", OtherKey="MaTour", IsForeignKey=true)]
		public Table_Tour Table_Tour
		{
			get
			{
				return this._Table_Tour.Entity;
			}
			set
			{
				Table_Tour previousValue = this._Table_Tour.Entity;
				if (((previousValue != value) 
							|| (this._Table_Tour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_Tour.Entity = null;
						previousValue.Table_ChiTietDonTours.Remove(this);
					}
					this._Table_Tour.Entity = value;
					if ((value != null))
					{
						value.Table_ChiTietDonTours.Add(this);
						this._MaTour = value.MaTour;
					}
					else
					{
						this._MaTour = default(int);
					}
					this.SendPropertyChanged("Table_Tour");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
